apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - skillcards.yaml
  - skillcollection.yaml
  - llmprovider.yaml
  - agents.yaml
  - agentplan.yaml
  - agentrun.yaml
  - agentplanrun.yaml
